"""Evaluates the pre-registered criteria (CAUSAL_PROTOCOL v1.1 §4) on out/causal/trials.parquet and writes report.md + figures."""
from __future__ import annotations
import json, os, sys
import numpy as np, pandas as pd
import matplotlib; matplotlib.use("Agg"); import matplotlib.pyplot as plt

OUT = sys.argv[1] if len(sys.argv) > 1 else "out/causal"
FRONT_LAT = [0, 45, 90, 135, 225, 270, 315]; LATERAL = [45, 90, 135, 225, 270, 315]; MEDFAST = ["medium", "fast"]

def ci(x, n=1000, seed=2026):
    rng = np.random.default_rng(seed); x = np.asarray(x, float); x = x[~np.isnan(x)]
    if len(x) == 0: return (np.nan, np.nan)
    m = np.array([rng.choice(x, len(x)).mean() for _ in range(n)]); return float(np.percentile(m, 2.5)), float(np.percentile(m, 97.5))

def main():
    df = pd.read_parquet(f"{OUT}/trials.parquet"); df["flee"] = (df["d_away"] > 0.02).astype(float)
    A = df[df.arm == "A"]; B = df[df.arm == "B"]; C = df[df.arm == "C"]; D = df[df.arm == "D"]; E = df[df.arm == "E"]
    lines = []; L = lines.append
    L("# Causal report - That Damn Fly M0\n"); L(f"Protocol {df['protocol'].iloc[0]} · model `{df['model_id'].iloc[0]}` · {len(df)} trials · {df.seed.max()} seeds per condition · arms {sorted(df.arm.unique())}\n")
    L("Generated by `scripts/causal_report.py`. Values **observed** in trials with the real FlyCore runtime; interpretations are marked as *inferred*.\n")
    # ---- 4.1
    L("## 4.1 Minimum response in the intact circuit (arm A)\n")
    res41 = {}
    g = A[A.speed_name.isin(MEDFAST)].groupby("dir_deg")
    tab = g.agg(n_dn=("n_dn", "mean"), n_base=("n_base", "mean"), li=("li", "mean"), d_away=("d_away", "mean"), d_sd=("d_away", "std"), flee=("flee", "mean"), v_peak=("v_peak", "mean")).round(3)
    L(tab.to_markdown()); L("")
    a_ok = all(tab.loc[d, "n_dn"] >= 3 * max(tab.loc[d, "n_base"], 1e-9) for d in FRONT_LAT)
    b_ok = all(tab.loc[d, "li"] >= 0.30 for d in LATERAL)
    c_ok = all(tab.loc[d, "d_away"] >= 0.05 for d in FRONT_LAT)
    d_ok = all(tab.loc[d, "flee"] >= 0.65 for d in FRONT_LAT)
    res41 = {"a_evoked_ge_3x_base": a_ok, "b_LI_ge_0.30": b_ok, "c_d_away_ge_0.05": c_ok, "d_flee_ge_0.65": d_ok}
    for k, v in res41.items(): L(f"- {k}: **{'PASS' if v else 'FAIL'}**")
    L(f"- 180° (reported, outside the criteria): d_away={tab.loc[180,'d_away']:.3f}, flee={tab.loc[180,'flee']:.2f}, n_dn={tab.loc[180,'n_dn']:.1f}\n")
    # per intensity
    L("### Per intensity (arm A, mean over frontal/lateral directions)\n")
    ti = A[A.dir_deg.isin(FRONT_LAT)].groupby("speed_name").agg(n_dn=("n_dn", "mean"), li=("li", "mean"), d_away=("d_away", "mean"), d_sd=("d_away", "std"), flee=("flee", "mean"), v_peak=("v_peak", "mean")).round(3)
    L(ti.to_markdown()); L("")
    # ---- 4.2
    L("## 4.2 Reduction by VPN→DN ablation (arm B vs A) - primary metric D_away\n")
    rows = []
    for (d, sn), gA in A.groupby(["dir_deg", "speed_name"]):
        gB = B[(B.dir_deg == d) & (B.speed_name == sn)]
        xa = gA.sort_values("seed")["d_away"].values; xb = gB.sort_values("seed")["d_away"].values
        mA, mB = xa.mean(), xb.mean(); R = 1 - mB / mA if mA > 0 else np.nan
        rng = np.random.default_rng(2026); boots = []
        for _ in range(1000):
            idx = rng.integers(0, len(xa), len(xa)); ma = xa[idx].mean(); mb = xb[idx].mean(); boots.append(1 - mb / ma if ma > 0 else np.nan)
        boots = np.array(boots); boots = boots[~np.isnan(boots)]
        rows.append(dict(dir_deg=d, speed=sn, d_away_A=mA, sd_A=xa.std(), d_away_B=mB, sd_B=xb.std(), R=R, R_lo=np.percentile(boots, 2.5) if len(boots) else np.nan, R_hi=np.percentile(boots, 97.5) if len(boots) else np.nan,
                         n_dn_A=gA.n_dn.mean(), n_dn_B=gB.n_dn.mean(), flee_A=gA.flee.mean(), flee_B=gB.flee.mean(), eligible=(mA >= 0.05) and (d != 180)))
    R = pd.DataFrame(rows); R.to_csv(f"{OUT}/reduction_B_vs_A.csv", index=False)
    L(R.round(3).to_markdown(index=False)); L("")
    el = R[R.eligible]
    medR = float(el.R.median()) if len(el) else np.nan
    frac = float(((el.R >= 0.30) & (el.R_lo > 0)).mean()) if len(el) else np.nan
    pass42 = bool(len(el) and medR >= 0.30 and frac >= 0.75)
    L(f"- Eligible conditions (A ≥ 0.05 W, ≠180°): {len(el)} of {len(R)}\n- Median R: **{medR:.3f}** (criterion ≥ 0.30)\n- Fraction with R ≥ 0.30 and lower CI > 0: **{frac:.2f}** (criterion ≥ 0.75)\n- 4.2: **{'PASS' if pass42 else 'FAIL'}**\n")
    L(f"- Secondary (eligible): mean reduction in N_DN = {1 - el.n_dn_B.sum() / max(el.n_dn_A.sum(), 1e-9):.3f}; flee A = {el.flee_A.mean():.2f} → B = {el.flee_B.mean():.2f}\n")
    # ---- 4.3 D
    L("## 4.3 Shuffled-weights control (arm D)\n")
    tD = D[D.speed_name.isin(MEDFAST)].groupby("dir_deg").agg(n_dn=("n_dn", "mean"), li=("li", "mean"), d_away=("d_away", "mean"), flee=("flee", "mean")).round(3)
    L(tD.to_markdown()); L("")
    d_b = all(tD.loc[d, "li"] >= 0.30 for d in LATERAL if not np.isnan(tD.loc[d, "li"])) and not tD.loc[LATERAL, "li"].isna().all()
    d_c = all(tD.loc[d, "d_away"] >= 0.05 for d in FRONT_LAT)
    pass43 = not (d_b and d_c)
    L(f"- Does D meet 4.1(b)? {d_b} · Does D meet 4.1(c)? {d_c} → 4.3: **{'PASS' if pass43 else 'FAIL'}** (the control must not meet both)\n")
    # ---- 4.4 C
    L("## 4.4 Motor output ablation (arm C)\n")
    mC = float(C.d_away.mean()); loC, hiC = ci(C.d_away.values)
    pass44 = abs(mC) <= 0.02
    L(f"- Mean D_away = {mC:.4f} W (95 % CI {loC:.4f}…{hiC:.4f}); mean n_dn = {C.n_dn.mean():.1f} (the network responds; the body does not) → 4.4: **{'PASS' if pass44 else 'FAIL'}**\n")
    # ---- 4.5 E
    L("## 4.5 No stimulus (arm E)\n")
    mE = float(E.d_away.mean()); loE, hiE = ci(E.d_away.values)
    pass45 = abs(mE) <= 0.02
    L(f"- Mean D_away = {mE:.4f} W (95 % CI {loE:.4f}…{hiE:.4f}); mean n_dn = {E.n_dn.mean():.2f} → 4.5: **{'PASS' if pass45 else 'FAIL'}**\n")
    # ---- decision
    allpass = all(res41.values()) and pass42 and pass43 and pass44 and pass45
    L("## Decision\n"); L(f"**{'PASSES' if allpass else 'DOES NOT PASS'}** the pre-registered criteria v1.1.\n")
    L("## Variability across seeds (arm A, D_away, W)\n")
    tv = A.groupby(["dir_deg", "speed_name"])["d_away"].agg(["mean", "std", "median", lambda x: np.percentile(x, 25), lambda x: np.percentile(x, 75), "min", "max"]).round(3)
    tv.columns = ["mean", "sd", "median", "q25", "q75", "min", "max"]; L(tv.to_markdown()); L("")
    L("## Limitations (inferred)\n")
    L("- The model resolves left/right (hemispheres), not front/back: the DN readout does not distinguish sectors 1 vs 3 of the same hemisphere; 180° is not a criterion.")
    L("- Per-sector retinotopy (H1) is assigned, not measured; the MaleCNS flat files carry no receptive fields.")
    L("- L/R reconstruction asymmetry (LC4 71 L vs 55 R; LC4→DNp04 6,811 vs 4,786 synapses) compensated only in the input gain (p2); it persists in the weights.")
    L("- LIF parameters/scale/inputs are choices calibrated on a frontal stimulus; they are not biophysical measurements.")
    L("- Ablation B removes every direct VPN→DN edge; indirect VPN→interneuron→DN paths remain - the residual response in B is real and reported.")
    L("- The virtual body is a stylized kinematic model; the wandering (H6) is a stochastic process independent of threats, identical across arms.")
    L("- The wandering (H6) drifts forward (0.18 W·s⁻¹): per direction, arms B/C/E show a direction-dependent baseline of D_away (negative for frontal threats, positive for rear ones). That is why R can exceed 1 and why the ablated body \"walks into the threat\" frontally - it is not attraction.")
    L("- No claim of a complete brain, consciousness, pain, learning or biological validation of the escape.")
    open(f"{OUT}/report.md", "w", encoding="utf-8").write("\n".join(lines))
    json.dump({"4.1": res41, "4.2": {"pass": pass42, "median_R": medR, "frac": frac}, "4.3": pass43, "4.4": pass44, "4.5": pass45, "all_pass": allpass}, open(f"{OUT}/verdict.json", "w"), indent=2)
    # figures
    fig, axes = plt.subplots(1, 3, figsize=(15, 4))
    for arm, col in [("A", "#2755A5"), ("B", "#AF3D2F"), ("C", "#555E55"), ("D", "#CBD3B9"), ("E", "#F4CD3C")]:
        s = df[(df.arm == arm) & (df.speed_name == "medium")].groupby("dir_deg")
        axes[0].plot(s.d_away.mean().index, s.d_away.mean().values, "o-", color=col, label=arm)
        axes[1].plot(s.n_dn.mean().index, s.n_dn.mean().values, "o-", color=col, label=arm)
        axes[2].plot(s.li.mean().index, s.li.mean().values, "o-", color=col, label=arm)
    axes[0].axhline(0.05, ls="--", c="k", lw=0.8); axes[0].set_title("D_away (W), medium speed"); axes[1].set_title("N_DN (400 ms)"); axes[2].set_title("LI"); axes[2].axhline(0.3, ls="--", c="k", lw=0.8)
    for ax in axes: ax.set_xlabel("direction (°)"); ax.legend(fontsize=8)
    plt.tight_layout(); plt.savefig(f"{OUT}/fig_by_direction.png", dpi=120)
    print(open(f"{OUT}/report.md", encoding="utf-8").read()[:6000])

if __name__ == "__main__":
    main()
