// GENERATED by tools/gen-model-config.py from research/models/tdf-escape-v0.1-p2.tdfm - do not edit by hand.
namespace ThatDamnFly.Simulation
{
    public static class ModelConfigValues
    {
        public const string ModelId = "tdf-escape-v0.1-p2";
        public const string FileName = "tdf-escape-v0.1-p2.tdfm";
        public const string ExpectedFileSha256 = "6ed1086387d81c9ce4508a05768f359c126a6271393b943f9ec941def494b7e8";
        public const long ExpectedBytes = 452132;
        /// <summary>Base URL for the apps (Android/iOS). On the web the page origin is used. Set before publication (E3).</summary>
        public const string RemoteBaseUrl = "https://thatdamnfly.com/model/";
    }
}
