// Body parity v1.6 (food, horsefly, boss, bait): C# (game) ↔ Python (research/tdf/body.py; fixture generated by research/scripts/body_fixture.py with the same motor stimulus). Tolerance for float32 vs float64.
using System.IO;
using System.Text.Json;
using ThatDamnFly.Domain;
using ThatDamnFly.Simulation;
using Xunit;

public class BodyParityTests
{
    [Fact]
    public void Body_matches_python_reference_within_tolerance()
    {
        var rows = JsonDocument.Parse(File.ReadAllText(Path.Combine(System.Environment.GetEnvironmentVariable("TDF_FIXTURE_DIR") ?? System.AppContext.BaseDirectory, "body_fixture.json"))).RootElement;
        int checkedRows = 0;
        var food = new[] { new FoodSpot(0.54f, 0.48f, 0.07f), new FoodSpot(0.175f, 0.47f, 0.06f) };
        foreach (var kind in new[] { "house", "fruitfly", "horsefly", "boss", "house_bait" })
            for (int seed = 1; seed <= 8; seed++)
            {
                bool bait = kind == "house_bait";
                var def = kind.StartsWith("house") ? FlyKinds.House : (kind == "fruitfly" ? FlyKinds.FruitFly : (kind == "boss" ? FlyKinds.Boss : FlyKinds.Horsefly));
                var body = BodyController.EdgeEntry((ulong)seed, BodyParams.For(def, 2, food));
                var motor = new float[8]; int took = 0, landed = 0;
                for (int t = 0; t < 300; t++)
                {
                    System.Array.Clear(motor, 0, 8); if (t >= 100 && t < 130) { motor[0] = 0.4f; motor[1] = 0.9f; }
                    if (bait) body.Bait = t >= 40 && t < 240 ? new FoodSpot(0.5f, 0.6f, 0.05f) : (FoodSpot?)null;   // v1.6: bait on ticks 40–239
                    body.Step(motor); if (body.TookOff) took++; if (body.Landed) landed++;
                    foreach (var r in rows.EnumerateArray())
                    {
                        if (r.GetProperty("seed").GetInt32() != seed || r.GetProperty("kind").GetString() != kind || r.GetProperty("t").GetInt32() != t + 1) continue;
                        Assert.True(System.Math.Abs(r.GetProperty("x").GetDouble() - body.Position.X) < 2e-3 && System.Math.Abs(r.GetProperty("y").GetDouble() - body.Position.Y) < 2e-3, $"seed {seed} {kind} t={t + 1}: py=({r.GetProperty("x").GetDouble()},{r.GetProperty("y").GetDouble()}) cs={body.Position}");
                        checkedRows++;
                    }
                }
                foreach (var r in rows.EnumerateArray())
                    if (r.GetProperty("seed").GetInt32() == seed && r.GetProperty("kind").GetString() == kind && r.GetProperty("t").GetInt32() == -1)
                    { Assert.Equal(r.GetProperty("took").GetInt32(), took); Assert.Equal(r.GetProperty("landed").GetInt32(), landed); checkedRows++; }
            }
        Assert.Equal(40 * 7, checkedRows);
    }
}
