"""Generates flycore_amalgam.cpp (header + sha256 + flycore) for Unity's Plugins/WebGL and Plugins/iOS.
Usage: python flycore/tools/amalgamate.py"""
import os, re, hashlib
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
def read(p): return open(os.path.join(root, p), encoding="utf-8").read()
hdr = read("include/flycore.h"); sha_h = read("src/sha256.h"); sha_c = read("src/sha256.cpp"); core = read("src/flycore.cpp")
sha_c = sha_c.replace('#include "sha256.h"', "")
core = core.replace('#include "flycore.h"', "").replace('#include "sha256.h"', "").replace("#define FC_BUILD 1", "")
out = ("// FlyCore amalgamation - GENERATED by flycore/tools/amalgamate.py; do not edit. Source: flycore/include + flycore/src.\n"
       "// Compiled by Unity (Emscripten) on Web and by Xcode on iOS. Static linking: FC_STATIC.\n"
       "#ifndef FC_STATIC\n#define FC_STATIC 1\n#endif\n#define FC_BUILD 1\n" + hdr + "\n" + sha_h + "\n" + sha_c + "\n" + core)
dst = [os.path.join(root, "..", "app", "Assets", "Plugins", "WebGL", "flycore_amalgam.cpp"), os.path.join(root, "..", "app", "Assets", "Plugins", "iOS", "flycore_amalgam.cpp")]
for d in dst:
    os.makedirs(os.path.dirname(d), exist_ok=True); open(d, "w", encoding="utf-8", newline="\n").write(out)
print("amalgam sha256", hashlib.sha256(out.encode()).hexdigest()[:16], "->", [os.path.relpath(d, root) for d in dst])
