"""Regenerates app/Assets/Game.Simulation/ModelConfigValues.cs from the model in research/models (real hash and size)."""
import hashlib, json, os, sys
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
mid = sys.argv[1] if len(sys.argv) > 1 else "tdf-escape-v0.1-p2"
p = os.path.join(root, "research", "models", mid + ".tdfm"); data = open(p, "rb").read(); h = hashlib.sha256(data).hexdigest()
man = json.load(open(os.path.join(root, "research", "models", mid + ".manifest.json"), encoding="utf-8")); assert man["file_sha256"] == h
remote = sys.argv[2] if len(sys.argv) > 2 else "https://thatdamnfly.com/model/"
src = f'''// GENERATED by tools/gen-model-config.py from research/models/{mid}.tdfm - do not edit by hand.
namespace ThatDamnFly.Simulation
{{
    public static class ModelConfigValues
    {{
        public const string ModelId = "{mid}";
        public const string FileName = "{mid}.tdfm";
        public const string ExpectedFileSha256 = "{h}";
        public const long ExpectedBytes = {len(data)};
        /// <summary>Base URL for the apps (Android/iOS). On the web the page origin is used. Set before publication (E3).</summary>
        public const string RemoteBaseUrl = "{remote}";
    }}
}}
'''
open(os.path.join(root, "app", "Assets", "Game.Simulation", "ModelConfigValues.cs"), "w", encoding="utf-8", newline="\n").write(src); print(mid, h, len(data))
